targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            "{{{{dir}}}}/{{{{file}}}}.dart": "{{{{dir}}}}/.generated/{{{{file}}}}.g.dart"

      json_serializable:
        options:
          generic_argument_factories: true
          explicit_to_json: true

      freezed:
        options:
          from_json: true
          to_json: true
          when:
            when: false
            maybe_when: false
            when_or_null: false
          build_extensions:
            "{{{{dir}}}}/{{{{file}}}}.dart": "{{{{dir}}}}/.generated/{{{{file}}}}.freezed.dart"
