name: fstruct_init
description: "A brick for populating a new projects with an opinionated file structure."
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: "^3.6.0"

dependencies:
  mason: ^0.1.0
  mason_function_extensions:
    git:
      url: "https://github.com/joshthedevelopa/mason_bricks.git"
      ref: main
      path: "tools/mason_function_extensions"
